name: flutter_babycare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.3
  http: ^0.13.4
  shared_preferences: ^2.0.8
  flutter_svg: ^1.0.3
  rxdart: ^0.27.2
  url_launcher: ^6.1.2
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^2.1.0
  curved_navigation_bar: ^1.0.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_database: ^6.0.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  equatable: ^2.0.3
  syncfusion_flutter_datepicker: ^19.3.55
  image_picker: ^0.8.4+4
  syncfusion_flutter_sliders: ^19.3.55
  uuid: ^3.0.5
  date_util: ^0.1.4
  dialog_flowtter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/chat.svg
    - assets/icon/home.svg
    - assets/icon/notify_badged.svg
    - assets/icon/notify.svg
    - assets/icon/user.svg
    - assets/icon/facebook.svg
    - assets/icon/google.svg
    - assets/icon/login_user.svg
    - assets/icon/login_password.svg
    - assets/icon/false.svg
    - assets/icon/true.svg
    - assets/icon/unobscure.svg
    - assets/icon/add.svg
    - assets/icon/gender_boy.svg
    - assets/icon/gender_girl.svg
    - assets/icon/date.svg
    - assets/icon/person.svg
    - assets/icon/porridge.svg
    - assets/icon/milk.svg
    - assets/icon/meat.svg
    - assets/icon/fish.svg
    - assets/icon/egg.svg
    - assets/icon/green_vegets.svg
    - assets/icon/red_vegets.svg
    - assets/icon/citrus_fruit.svg
    - assets/icon/carbohydrate.svg
    - assets/icon/fat.svg
    - assets/icon/protein.svg
    - assets/icon/vitamin_a.svg
    - assets/icon/vitamin_b.svg
    - assets/icon/vitamin_c.svg
    - assets/icon/vitamin_d.svg
    - assets/icon/iron.svg
    - assets/icon/calcium.svg
    - assets/icon/iodine.svg
    - assets/icon/info.svg
    - assets/icon/achievement.svg
    - assets/icon/warn.svg
    - assets/icon/book.svg
    - assets/icon/arrow_back.svg
    - assets/icon/send.svg
    - assets/icon/send_inactive.svg
    - assets/icon/cart.svg
    - assets/icon/shopee.svg
    - assets/icon/star_active.svg
    - assets/icon/star_inactive.svg

    - assets/image/default_baby.png
    - assets/image/EmojiLove_1.png
    - assets/image/EmojiHappy_2.png
    - assets/image/EmojiSmile_3.png
    - assets/image/EmojiSad_4.png
    - assets/image/EmojiCry_5.png
    - assets/image/meal_suggestion.jpg
    - assets/image/vaccine_suggestion.jpg
    - assets/image/vaccination_history.jpg
    - assets/image/logo_s150.png
    # Authenticate gg API
    - assets/babycare-caug-5734d56d8adc.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
